### ISSUE TITLE
Is it possible to create a pyvips build for osx-arm64?

### ISSUE THREAD

**Issue by bencomp** [conda-forge/pyvips-feedstock#9]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: I would like to run an application that depends on pyvips on an Apple MacBook with M1 chipset, but pyvips is only built for osx with x86_64 processors. Would it be possible to add the `osx-arm64` target platform to the feedstock?

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : kraken
    active env location : /opt/homebrew/Caskroom/miniforge/base/envs/kraken
            shell level : 2
       user config file : /Users/user/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __osx=11.5.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/user/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.2 Darwin/20.6.0 OSX/11.5.1
                UID:GID : 656009039:208802054
             netrc file : None
           offline mode : False
```
</details>

**Comment by hmaarrfk** [comment]
Yes it is.

The correct place to make these requests is:

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1754

You may simply add a package to the osx_arm64 migration if you need. All depending packages will also be migrated.

You can track progress 
https://conda-forge.org/status/

**Comment by bencomp** [comment]
Wow, thanks for the quick response! I wasn't aware of this workflow and I'm grateful for how it's been picked up :)
